"""Run the auditable two-model quality-aware routing policy."""
from __future__ import annotations
import argparse, json
from pathlib import Path
import numpy as np, pandas as pd, torch
from torch.utils.data import DataLoader
from train_baseline import CheXpertDataset, make_model, predict_outputs

def entropy(p): return float(-(p * np.log(np.clip(p, 1e-7, 1))).sum())

def main():
    p=argparse.ArgumentParser(); p.add_argument("--manifest",type=Path,required=True); p.add_argument("--data-root",type=Path,required=True); p.add_argument("--model1",type=Path,required=True); p.add_argument("--model2",type=Path,required=True); p.add_argument("--split",choices=["route_validation","official_valid"],required=True); p.add_argument("--split-column",default="agent_split"); p.add_argument("--qc",type=Path); p.add_argument("--temperature1",type=float,default=1.0); p.add_argument("--temperature2",type=float,default=1.0); p.add_argument("--image-size",type=int,default=320); p.add_argument("--batch-size",type=int,default=16); p.add_argument("--num-workers",type=int,default=2); p.add_argument("--theta-uncertain",type=float,default=.4); p.add_argument("--theta-quality",type=float,default=3.0); p.add_argument("--theta-call",type=float,default=.3); p.add_argument("--theta-accept-disagreement",type=float,default=.1); p.add_argument("--theta-pos",type=float,default=.8); p.add_argument("--theta-neg",type=float,default=.2); p.add_argument("--output",type=Path,required=True); args=p.parse_args()
    ck1=torch.load(args.model1,map_location="cpu"); ck2=torch.load(args.model2,map_location="cpu"); nc1=int(ck1.get("num_classes",3)); nc2=int(ck2.get("num_classes",3)); df=pd.read_csv(args.manifest); df=df[df[args.split_column].eq(args.split)].copy(); device=torch.device("cuda" if torch.cuda.is_available() else "cpu"); m1=make_model(nc1,ck1.get("arch","densenet121")).to(device); m2=make_model(nc2,ck2.get("arch","resnet50")).to(device); m1.load_state_dict(ck1["model"]); m2.load_state_dict(ck2["model"]); loader=DataLoader(CheXpertDataset(df,args.data_root,args.image_size,False,3),batch_size=args.batch_size,shuffle=False,num_workers=args.num_workers); l1,y=predict_outputs(m1,loader,device); l2,_=predict_outputs(m2,loader,device); pr1=torch.softmax(torch.from_numpy(l1/args.temperature1),dim=1).numpy(); pr2=torch.softmax(torch.from_numpy(l2/args.temperature2),dim=1).numpy(); q=pd.read_csv(args.qc) if args.qc else pd.DataFrame(index=range(len(df))); rows=[]
    for i,(_,r) in enumerate(df.reset_index(drop=True).iterrows()):
        p1=pr1[i]; hard=bool(q.iloc[i].get("hard_fail",False)) if len(q)>i else False; reasons=str(q.iloc[i].get("hard_fail_reasons","")) if len(q)>i else ""; lateral=str(r.get("Frontal/Lateral","Frontal")) != "Frontal"; quality=float(q.iloc[i].get("quality_risk",0.0)) if len(q)>i else 0.; trigger="hard_fail" if hard else "lateral" if lateral else "quality" if quality>=args.theta_quality else "uncertainty" if p1[2]>=args.theta_uncertain else "confidence" if not (p1[1]>=args.theta_pos or p1[1]<=args.theta_neg) else "none"; called=trigger not in {"hard_fail","lateral","quality","none"}; action="DEFER_TO_HUMAN" if trigger in {"hard_fail","lateral","quality"} else "ACCEPT" if not called else "DEFER_TO_HUMAN"; p2=None; disagreement=None; fused=None
        if called:
            p2=pr2[i]; disagreement=float(abs(p1[1]-p2[1])); fused=float((p1[1]+p2[1])/2); action="ACCEPT" if disagreement<=args.theta_accept_disagreement and (fused>=args.theta_pos or fused<=args.theta_neg) else "DEFER_TO_HUMAN"
        rows.append({"Path":r.get("Path",""),"Patient":r.get("Patient",""),"Study":r.get("Study",""),"label":int(y[i]),"p1_negative":float(p1[0]),"p1_uncertain":float(p1[2]),"p1_positive":float(p1[1]),"entropy":entropy(p1),"trigger":trigger,"model2_called":called,"p2_positive":None if p2 is None else float(p2[1]),"disagreement":disagreement,"fused_positive":fused,"action":action,"hard_fail":hard,"hard_fail_reasons":reasons})
    out=pd.DataFrame(rows); args.output.parent.mkdir(parents=True,exist_ok=True); out.to_csv(args.output,index=False); summary={"split":args.split,"rows":len(out),"accept_rate":float((out.action=="ACCEPT").mean()),"model2_call_rate":float(out.model2_called.mean()),"defer_rate":float((out.action=="DEFER_TO_HUMAN").mean()),"lateral_rate":float((out.trigger=="lateral").mean()),"hard_fail_rate":float(out.hard_fail.mean())}; (args.output.with_suffix(".json")).write_text(json.dumps(summary,indent=2),encoding="utf-8"); print(json.dumps(summary,indent=2))
if __name__ == "__main__": main()
